version: '3'
services:
    amplify:
        image: tanabebe/meet-amplify-demo:latest
        volumes:
            - ./:/app/amplify-demo/react-app:cached
            - ./aws/:/root/.aws/
            - /app/amplify-demo/react-app/node_modules
        ports:
            - "3001:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true