version: '3'
services:
    amplify:
        image: tanabebe/meet-amplify-demo:latest
        volumes:
            - ./:/app/amplify-demo/:cached
            - ./aws/:/root/.aws/
            - /app/amplify-demo/react-app/node_modules
        ports:
            - '3000:3000'
            - '3001:3001'
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true